### ISSUE TITLE
`create-fself` crashes with SIGSEGV when linking with `--gc-sections --as-needed`

### ISSUE THREAD

**Issue by glebm** [PacBrew/ps4-openorbis#8]
When linking with `--gc-sections --as-needed`, `create-fself` crashes with SIGSEGV

```
FAILED: devilutionx.self /home/gleb/devilutionX/build-ps4/devilutionx.self 
cd /home/gleb/devilutionX/build-ps4 && /usr/bin/cmake -E env OO_PS4_TOOLCHAIN=/opt/pacbrew/ps4/openorbis /opt/pacbrew/ps4/openorbis/bin/create-fself -in=devilutionx -out=devilutionx.oelf --eboot eboot.bin --paid 0x3800000000000035 --authinfo 000000000000000000000000001C004000FF000000000080000000000000000000000000000000000000008000400040000000000000008000000000000000080040FFFF000000F000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4bd64b]

goroutine 1 [running]:
github.com/OpenOrbis/create-fself/pkg/oelf.(*OrbisElf).GenerateProgramHeaders(0xc000185680)
	/home/cpasjuste/dev/pacbrew-packages/ps4-openorbis/create-fself/src/create-fself-30d2e10507f55124cf21e85e19825482e4f93c87/pkg/oelf/OELFGenProgramHeaders.go:116 +0x3ab
main.main()
	/home/cpasjuste/dev/pacbrew-packages/ps4-openorbis/create-fself/src/create-fself-30d2e10507f55124cf21e85e19825482e4f93c87/cmd/create-fself/main.go:94 +0x517
ninja: build stopped: subcommand failed.
```

More log: https://gist.githubusercontent.com/glebm/49a29bfc641ea3c844cadd08ef18df68/raw/c2ac2268dba8f3c6ec4b69fca7ec4eecf8dbbc33/gistfile1.txt

**Comment by glebm** [comment]
Moved to the `create-fself` repository https://github.com/OpenOrbis/create-fself/issues/6
